language: cpp

branches:
  only:
   - master

compiler: 
   - g++

sudo : required

before_script: 
   - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
   - sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0.1/ubuntu/ trusty universe'
   - sudo apt-get update
   - sudo apt-get install -y libwxbase3.0-dev libwxgtk3.0-dev wx3.0-headers wx-common libwxbase3.0-dbg libwxgtk3.0-dbg
   - sudo ln -sv wx-3.0/wx wx

script:
  - make Makefile
