language: cpp

branches:
  only:
   - master

compiler: 
   - g++

sudo : required

before_script: 
  - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  - sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0.2/ubuntu/ precise universe'
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
 
  - sudo apt-get install -y liblzma5 libjbig0 libpango1.0-0 libwxbase3.0-0-unofficial libwxbase3.0-dev libwxgtk3.0-0-unofficial libwxgtk3.0-dev wx3.0-headers wx-common wx3.0-i18n libcppunit-dev libsqlite3-dev

  - sudo mv /usr/include/wx-3.0-unofficial/wx /usr/include/wx
  - sudo mkdir /usr/include/SQLite && sudo mv /usr/include/sqlite3.h /usr/include/SQLite/sqlite3.h
  - ls -la /usr/include/
  
script:
  - make
  
  
  