language: cpp

branches:
  only:
   - master

compiler: 
   - g++

sudo : required

before_script: 
   - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
   - sudo apt-get update
   - sudo apt-get install -y  install libwxbase3.1-dev libwxgtk3.1-dev wx3.1-headers wx-common libwxbase3.1-dbg libwxgtk3.1-dbg
   - sudo ln -sv wx-3.1/wx wx

script:
  - make Makefile
