language: cpp

branches:
  only:
   - master

compiler: 
   - g++

before_script: "sudo yum install wxGTK-devel wxBase && sudo ln -sv wx-2.8/wx wx"

sudo : required

script:
  - make Makefile && ./bin/GestNote